### ISSUE TITLE
Installing from PyPI

### ISSUE THREAD

**Issue by JRickMaster** [kevinjwalters/Adafruit_CircuitPython_SPS30#1]
Hi Kevinjwalter, I´m trating to install the driver locally but that doesnt work and display in terminal Rpi4 - Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/adafruit-circuitpython-sps30/ -
Maybe I´m make some wrong becouse the code will indicate that the module named 'adafruit_sps30' doesnt exist.

**Comment by kevinjwalters** [comment]
It's not been adopted (yet!) by Adafruit and isn't on pypi. The library is intended to work with CircuitPython. I've not used it myself but on the Raspberry Pi Adafruit have a Blinka layer which allows these libraries to be used from Python code there. Are you using that? It's documented on https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

If you have that then you can just download the library from GitHub.

I still have to finish adding support for some of the less common SPS30 commands and I think I'm going to add a very short pause to stop bad data when the floating point / integer mode is selected or changed to prevent bad data coming back.

**Comment by kevinjwalters** [comment]
Ah, I see the [README.rst](https://github.com/kevinjwalters/Adafruit_CircuitPython_SPS30#readme) is a bit confusing in its current state. It's the standard page for libraries but it's not accurate at the moment as the library hasn't been adopted and published out to pypi.

**Comment by JRickMaster** [comment]
Ooh! thanks so much for the explanation, so will I check the document that you tell me. I´m using a Raspberry Pi 4 to treats to make operate with python and using I2C communication.

Commonly I use the driver https://pypi.org/project/sps30/ to make the measures, and work very fine but when I put the sensor sps30 insade a inerter recipient and do circuler clean air to check that mesure keeping on zero, and alway send to me error while to approaching  zero so I wanna treate to proofe  whit another way and thats the reason.
But well I hoper early Adafruit adopted it soon to chech it. But I thing Its a grat idea add the commnds  to bad data that suposed is the problem that I commonly see whit my implementation.

If I´ve another hesitate I ask you.  8D

Thank you very much, you are amazing !!
